# rag-backend
stages:
  - build
  - deploy

variables:
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
  BACK_IMAGE: "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_PASSWORD:-$CI_JOB_TOKEN}" "$CI_REGISTRY"
  - cp $env_file .env

build:build_images:
  stage: build
  script:
    - export DOCKER_BUILDKIT=1
    - docker build -t "$BACK_IMAGE" -f Dockerfile .
    - docker push "$BACK_IMAGE"
  only:
    - main
  when: manual

deploy:deploy_prod:
  stage: deploy
  script:
    - export IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    - docker compose down || true
    - docker compose pull
    - docker compose up -d
    - docker compose ps
  tags:
    - md-scribe-prod-runner
  only:
    - main
  when: manual

# Test build
build:build_test:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_PASSWORD:-$CI_JOB_TOKEN}" "$CI_REGISTRY"
    - cp "$env_file_test" .env
  script:
    - export DOCKER_BUILDKIT=1
    - docker build -t "$BACK_IMAGE" -f Dockerfile .
    - docker push "$BACK_IMAGE"
  only:
    - test
  when: manual

# Test deploy
deploy:deploy_test:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_PASSWORD:-$CI_JOB_TOKEN}" "$CI_REGISTRY"
    - cp "$env_file_test" .env
  script:
    - export IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    - docker compose down || true
    - docker compose pull
    - docker compose up -d
    - docker compose ps
  tags:
    - md-scribe-runner
  only:
    - test
  when: manual
