version: "3.9"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"

services:
  web:
    container_name: fastapi-template-web
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - infra/envs/.env.dev
    depends_on:
      - db

  db:
    container_name: fastapi-template-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      <<: *postgres-variables
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U postgres -d postgres"
      timeout: 2s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"  # browser access at localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data:
