"""add_telegram_chat_id_to_projects

Revision ID: 0a0b9ad52a1b
Revises: 176ab991976b
Create Date: 2026-05-18 03:33:48.272186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0b9ad52a1b'
down_revision: Union[str, None] = '176ab991976b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'telegram_chat_id')
    # ### end Alembic commands ###
