"""add faq categories

Revision ID: e1b2c3d4e5f7
Revises: d720bdf2d2a5
Create Date: 2026-03-26 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b2c3d4e5f7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_categories_id'), 'faq_categories', ['id'], unique=False)
    op.add_column('faqs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faqs', 'faq_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_column('faqs', 'category_id')
    op.drop_index(op.f('ix_faq_categories_id'), table_name='faq_categories')
    op.drop_table('faq_categories')
    # ### end Alembic commands ###
